// Generated by gencpp from file jsk_topic_tools/ListResponse.msg
// DO NOT EDIT!


#ifndef JSK_TOPIC_TOOLS_MESSAGE_LISTRESPONSE_H
#define JSK_TOPIC_TOOLS_MESSAGE_LISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jsk_topic_tools
{
template <class ContainerAllocator>
struct ListResponse_
{
  typedef ListResponse_<ContainerAllocator> Type;

  ListResponse_()
    : topic_names()  {
    }
  ListResponse_(const ContainerAllocator& _alloc)
    : topic_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _topic_names_type;
  _topic_names_type topic_names;





  typedef boost::shared_ptr< ::jsk_topic_tools::ListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_topic_tools::ListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListResponse_

typedef ::jsk_topic_tools::ListResponse_<std::allocator<void> > ListResponse;

typedef boost::shared_ptr< ::jsk_topic_tools::ListResponse > ListResponsePtr;
typedef boost::shared_ptr< ::jsk_topic_tools::ListResponse const> ListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_topic_tools::ListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jsk_topic_tools::ListResponse_<ContainerAllocator1> & lhs, const ::jsk_topic_tools::ListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.topic_names == rhs.topic_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jsk_topic_tools::ListResponse_<ContainerAllocator1> & lhs, const ::jsk_topic_tools::ListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jsk_topic_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_topic_tools::ListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_topic_tools::ListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_topic_tools::ListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f88f7a076bf16dde010b2480af40dcdb";
  }

  static const char* value(const ::jsk_topic_tools::ListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf88f7a076bf16ddeULL;
  static const uint64_t static_value2 = 0x010b2480af40dcdbULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_topic_tools/ListResponse";
  }

  static const char* value(const ::jsk_topic_tools::ListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] topic_names\n"
"\n"
;
  }

  static const char* value(const ::jsk_topic_tools::ListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topic_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_topic_tools::ListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_topic_tools::ListResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "topic_names: ";
    if (v.topic_names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.topic_names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.topic_names[i]);
    }
    if (v.topic_names.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_TOPIC_TOOLS_MESSAGE_LISTRESPONSE_H
